# Generated by Django 5.2.1 on 2025-05-27 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0002_actor_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakila.actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakila.film')),
            ],
            options={
                'db_table': 'film_actor',
                'unique_together': {('film', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='films', through='sakila.FilmActor', to='sakila.actor'),
        ),
    ]
